version: "3"
services:
  # Creates operator for testing
  token-exchange-init:
    image: ghcr.io/overmindtech/nats-token-exchange:main
    entrypoint: /workspace/.devcontainer/init-nsc.sh
    volumes:
      - nsc-storage:/nsc
      - ..:/workspace

  # Authenticted NATS for testing auth mechanisms
  nats-auth:
    image: nats
    command: "-c /nsc/nats-server.conf -DV" #-c /etc/nats/nats.conf --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222
    volumes:
      - nsc-storage:/nsc
    networks:
      - nats
    depends_on:
      token-exchange-init:
        condition: service_completed_successfully

  # Unauthenticated NATS for simpler testing
  nats:
    image: nats
    networks:
      - nats

  # Runs the token exchange
  nats-token-exchange:
    image: ghcr.io/overmindtech/nats-token-exchange:main
    command: run --nsc-operator overmind-testing --nsc-storage /nsc --auth0-domain dev-qsurrmp8.eu.auth0.com --nats-server nats://nats-auth:4222
    volumes:
      - nsc-storage:/nsc
    networks:
      - nats
    depends_on:
      token-exchange-init:
        condition: service_completed_successfully
      nats:
        condition: service_started

  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 1-bullseye
        NODE_VERSION: none
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - nats

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  nats:

volumes:
  nsc-storage: