version: "3"
services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/go:0-1-bullseye"
    volumes:
      - ..:/workspace:cached
      # mount the user's AWS config so that the CLI works as expected
      - ~/.aws:/home/vscode/.aws:cached
      # make the rest of the checkouts from the host available, so that
      # cross-mod changes can be developed and tested inside the container
      - ../..:/sources

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - nats

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # Authenticted NATS for testing auth mechanisms
  nats-auth:
    image: ghcr.io/overmindtech/test-populated-nats:main
    networks:
      - nats

  # Unauthenticated NATS for simpler testing
  nats:
    image: nats
    networks:
      - nats

  api-server:
    image: ghcr.io/overmindtech/test-populated-api-server:main
    command: --nats-url nats://nats-auth:4222 --disable-kube
    networks:
      - nats

networks:
  nats:

volumes:
  nsc-storage:
