name: Tests
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
    services:
      nats:
        image: nats
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
  
    - name: Test
      run: go test -timeout 30s ./...
